name: Feature Request (English)
description: Suggest an idea for this project
labels: [ "enhancement" ]
title: "[FR] "
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Make sure your feature request follows the checklist below.
      options:
        - label: No one has submitted a similar or identical feature request before.
          required: true
        - label: This suggestion does not depart from the original intention of Easter Eggs.
          required: true
  - type: textarea
    id: propose
    attributes:
      label: Proposed enhancement
      description: Propose of the enhancement.
      placeholder: |
        Show your idea here.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: What is your suggested solution for this enhancement?
      placeholder: |
        How do you think this should be done?
  - type: textarea
    id: addition
    attributes:
      label: Additional info
      description: Everything else you consider worthy that we did not ask for.
