name: Build Debug for PR

on:
  pull_request:
    paths:
      - 'app/**'
      - 'eggs/**'
      - 'basic/**'
      - 'feature/**'
      - 'core/**'
      - 'jvm-basic/**'
      - 'build-logic/**'
      - 'gradle/**'
      - '*.kts'
      - 'gradle.properties'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean app:assembleFossAlphaDebug
